### ISSUE TITLE
type-based constraints are slightly incorrect for positive numbers

### ISSUE THREAD

**Issue by paulswartz** [wesleyi23/GTFS-Frictionless#2]
https://github.com/wesleyi23/GTFS-Frictionless/blob/master/lookup_tables/type_based_constraints.csv

- "Positive integer" minimum should be 1
- "Positive float" minimum should be 1.175494e-38 (per https://stackoverflow.com/a/39232328)

**Comment by wesleyi23** [comment]
Thanks for looking at this. These are now updated.
