### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by barbeau** [wesleyi23/GTFS-Frictionless#4]
@wesleyi23 Thanks for all this work, it's great to see!

Could you add a license header for each file and a general license file in the repo?

Looks like Stephen Gate's original work is licensed under CC BY 4.0:
https://github.com/wesleyi23/GTFS-Frictionless

So it probably makes sense for any related/derivative content to be under that license?

FWIW, for code my personal preference is Apache v2.0.

**Comment by wesleyi23** [comment]
Done
